### ISSUE TITLE
Quaternion-to-matrix identity rotated

### ISSUE THREAD

**Issue by winduptoy** [recp/cglm#10]
I'm seeing the following behavior for quaternion to matrix conversion.

```
versor rotation = GLM_QUAT_IDENTITY_INIT;
fprintf(stderr, "-- Quaternion --\n%.4f %.4f %.4f %.4f\n\n", rotation[0], rotation[1], rotation[2], rotation[3]);

mat4 rotMatrix = GLM_MAT4_IDENTITY_INIT;
glm_quat_mat4(rotation, rotMatrix);
fprintf(stderr, "-- Matrix --\n%.4f %.4f %.4f %.4f\n%.4f %.4f %.4f %.4f\n%.4f %.4f %.4f %.4f\n%.4f %.4f %.4f %.4f\n", rotMatrix[0][0], rotMatrix[0][1], rotMatrix[0][2], rotMatrix[0][3], rotMatrix[1][0], rotMatrix[1][1], rotMatrix[1][2], rotMatrix[1][3], rotMatrix[2][0], rotMatrix[2][1], rotMatrix[2][2], rotMatrix[2][3], rotMatrix[3][0], rotMatrix[3][1], rotMatrix[3][2], rotMatrix[3][3]);
```
outputs
```
-- Quaternion --
0.0000 0.0000 0.0000 1.0000

-- Matrix --
-1.0000 0.0000 0.0000 0.0000
0.0000 -1.0000 0.0000 0.0000
0.0000 0.0000 1.0000 0.0000
0.0000 0.0000 0.0000 1.0000
```

The identity quaternion is what I expect, but the matrix seems to be flipped 180 degrees on X and Y. I noticed this because everything I render is flipped upside down. Shouldn't `rotMatrix[0][0]` and `rotMatrix[1][1]` equal positive 1 instead of negative 1 when using an identity quaternion? Or maybe I don't understand quaternions fully.

**Platform:**
Linux 64-bit
gcc v7.2.1
cglm v0.3.1

**Comment by winduptoy** [comment]
@recp Any ideas on this?

**Comment by recp** [comment]
@winduptoy sorry I didn't see this issue until now, fell free to ping me again

I think identity versor (GLM_QUAT_IDENTITY_INIT) is wrong. 
```C
GLM_QUAT_IDENTITY_INIT  {0.0f, 0.0f, 0.0f, 1.0f}
```

```C
versor rotation2;
glm_quat(rotation2, 0, 0, 0, 0);
```

gives {1.0f, 0.0f, 0.0f, 0.0f} so it must be 
```C
GLM_QUAT_IDENTITY_INIT  {1.0f, 0.0f, 0.0f, 0.0f}
```
but `GLM_QUAT_IDENTITY_INIT  {0.0f, 0.0f, 0.0f, 0.0f}` also seems valid for your case.  I'll fix this ASAP, but if you want to fix that, PR is welcome :)

`void glm_quat(versor q, float  angle, float  x,  float  y,  float  z);` this function also creates a versor. q is out parameter, I must change its name. 

Addition
---
You don't have to initialize **dest** (or out) parameters. In your case you dont have to initialize rotMatrix.
```C
mat4 rotMatrix;
glm_quat_mat4(rotation, rotMatrix);
```
would be enough, but since function is inline I think compiler will ignore identity initialization (I hope)

Also I would use built-in print utils to print them, it would save you to write huge printf :)

Print matrix: `glm_mat4_print(rotMatrix, stderr);`
Print Versor: `glm_versor_print(rotation2, stderr);`
Print Vec3:       `glm_vec3_print(vec, stderr)`
Print Vec4:    `glm_vec4_print(vec, stderr)`

**Comment by winduptoy** [comment]
Ah thank you for pointing out the print functions! I must have missed those. I'd like to help you with documentation soon.

I did not realize that cglm used `w, x, y, z`, I simply assumed it was `x, y, z, w`. I don't really have a preference, but I think it would be important to document this in a very visible place.

Thank you! Hope you had a good holiday wherever in the world you may be.

**Comment by recp** [comment]
> I'd like to help you with documentation soon.
That would be wonderful

> I did not realize that cglm used w, x, y, z, I simply assumed it was x, y, z, w. I don't really have a preference, but I think it would be important to document this in a very visible place.

I'm confused now, probably most people may assume that is x, y, z, w. For C++ classes probably most people accessing those values by ctor or its name like quat->x, quat->w so it doesn't matter for them I think, but since we have stored them as array order is matter. versor is stored as vec4 (aligned) because it is perfectly fits with SIMD instuctions to optimize them. Maybe documentation would prevent any confusion here

> Thank you! Hope you had a good holiday wherever in the world you may be.

Thank you very much, I hope you too.

**Comment by recp** [comment]
Fixed by: https://github.com/recp/cglm/pull/11

**Comment by recp** [comment]
Do not worry, you are welcome to ask anything!, it helps to improve this library.

cglm was used **wxyz** layout/order until this pull request: https://github.com/recp/cglm/pull/43 and version  v0.4.0. Check the last comment in PR ;)

Currently it must use **xyzw** and now quaternion api is more powerful than before. So last element is **w** now, it is real part yes. 

If there is a bug please let me know or try to fix it by a PR :)

**Comment by winduptoy** [comment]
Awesome, thanks for explanation. You're improving the library faster than I can keep up!

As always, thank you for this wonderful library and your excellent work.
