### ISSUE TITLE
A Function Returning the Current Version

### ISSUE THREAD

**Issue by moiri** [recp/cglm#116]
It would be nice if a function could be provided which returns the current version number of the library.

**Comment by recp** [comment]
Hi @moiri 

We have version (https://github.com/recp/cglm/blob/master/include/cglm/version.h) header which provides current version numbers. 

Similar header can be found at **libuv** library: 
https://github.com/libuv/libuv/blob/33cb9f4a3ff6aa44296690a87af5b781946de13f/include/uv/version.h

And function implementation (probably this is what you want):
https://github.com/libuv/libuv/blob/e4087dedf837f415056a45a838f639a3d9dc3ced/src/version.c

Since we have version header, do we still need a similar version function?

**Comment by moiri** [comment]
First-up, thank you for your answer and sorry for my (very) late reply.

The header definitions are perfectly fine for me. I think it might make sense to add a note on this in the API. Maybe under [utlis/helpers](https://cglm.readthedocs.io/en/latest/util.html)?

**Comment by recp** [comment]
That is a good idea to add version to documentation 👍

By starting now documentation about versioning should be able to seen at https://cglm.readthedocs.io/en/latest/version.html 

Maybe version.h must be included in `cglm/cglm.h` like others.
