### ISSUE TITLE
CMake Build Process?

### ISSUE THREAD

**Issue by ForeverZer0** [recp/cglm#117]
Was curious if there were any plans to add a CMake build system for this project?

I am admittedly not familiar enough with the Autotools build system, otherwise I would happily adapt it myself and and submit a pull request. Either way, thank you very much for creating and sharing.

**Comment by recp** [comment]
Hi @ForeverZer0 ,

I think we can support CMake build system. Any PR that implements CMake is welcome, otherwise I will implement that in my free time (I don't have enough it these days :( )

Also you don't have to build **cglm**, cglm provides both inline and library call optionally. All `glm_ ` functions are inline and all `glmc_` are library called function. `glmc_` functions are just wrappers for inline functions. Inline functions may increase binary size but they also come with speed. To use inline functions just include cglm header and then just use it ;)

**Comment by FMMazur** [comment]
Creating...

**Comment by recp** [comment]
Perfect! I'm waiting the PR 🤗

**Comment by recp** [comment]
@ForeverZer0 this is implemented at https://github.com/recp/cglm/pull/130 thanks to @FMMazur
