### ISSUE TITLE
Test failures on Raspberry Pi

### ISSUE THREAD

**Issue by PeterOGB** [recp/cglm#144]
Fresh clone from the repo, up to date Pi4:

make check

 assert fail in test/src/test_affine.h on line 536 :  ASSERT((glm_uniscaled)(m1))
  𐄂 glm_uniscaled 
  assert fail in test/src/test_affine.h on line 536 :  ASSERT((glmc_uniscaled)(m1))
  𐄂 glmc_uniscaled 
  assert fail in test/src/test_vec3.h on line 875 :  ASSERT(test_eq(v1[0], 0.0f))
  𐄂 glm_vec3_rotate_m4 
  assert fail in test/src/test_vec3.h on line 947 :  ASSERT(test_eq(v1[0], 0.0f))
  𐄂 glm_vec3_rotate_m3 
  assert fail in test/src/test_vec3.h on line 875 :  ASSERT(test_eq(v1[0], 0.0f))
  𐄂 glmc_vec3_rotate_m4 
  assert fail in test/src/test_vec3.h on line 947 :  ASSERT(test_eq(v1[0], 0.0f))
  𐄂 glmc_vec3_rotate_m3 
  assert fail in test/src/test_vec4.h on line 517 :  ASSERT(test_eq(v2[0] + v1[0] * s, v3[0]))
  𐄂 glm_vec4_muladds
  assert fail in test/src/test_vec4.h on line 517 :  ASSERT(test_eq(v2[0] + v1[0] * s, v3[0]))
  𐄂 glmc_vec4_muladds

cglm test results (0.59s):
--------------------------
635 tests are runned, 627 are passed, 8 are failed

PeterO

**Comment by recp** [comment]
Hi @PeterOGB 

Thanks for reporting the test results. I'll investigate this asap. 

May I ask what is your CPU model? I mean **cglm** uses SIMD (SSE2, AVX, ARM NEON) so it would be helpful to know if your CPU uses one of SIMD arch e.g neon, sse2, avx...

**Comment by PeterOGB** [comment]
On Tue, 2020-05-26 at 11:53 -0700, Recep Aslantas wrote:
> Hi @PeterOGB
> Thanks for reporting the test results. I'll investigate this asap.
> May I ask what is your CPU model? I mean cglm uses SIMD (SSE2, AVX, ARM NEON) so it
> would be helpful to know if your CPU uses one of SIMD arch e.g neon, sse2, avx...

Pi4 has a Quad core Cortex-A72 which has neon support.

PeterO

**Comment by recp** [comment]
@PeterOGB thanks for quick response, I'll take a look at

**Comment by recp** [comment]
@PeterOGB 

I think I may solved a few issues with these commits: 

https://github.com/recp/cglm/commit/a1485a14f6bb1dbd40cf52a472ca923db83c722e : option to override FLT_EPSILON with GLM_FLT_EPSILON
https://github.com/recp/cglm/commit/d2e5a3cd5b83c1abc6f4f800c3851c7d44109900 : use epsilon to compare `vec2/vec3/vec4_eq_all`
https://github.com/recp/cglm/commit/f49e8f99914e9739fef1daf47f58748cb749877d : neon: fix vec4_muladds (critical)

1. `glm_vec4_muladds` was using wrong instruction, probably copy-paste error
2. `glm_vec2_eq_all` now uses epsilon, because there may be floating point errors, for instance the extracted scale values were: `7.000000477 7.000000477 7.000000000` su using `==` for all values causes test fail...
3. You can change epsilon:

see `common.h`:
```C
#ifndef CGLM_USE_DEFAULT_EPSILON
#  ifndef GLM_FLT_EPSILON
#    define GLM_FLT_EPSILON 1e-6
#  endif
#else
#  define GLM_FLT_EPSILON FLT_EPSILON
#endif
```

Can you try again please?

I think we must add more tests and run ARM tests on Travis-CI...

**Comment by recp** [comment]
@PeterOGB 

I think I may solved a few issues with these commits: 

https://github.com/recp/cglm/commit/a1485a14f6bb1dbd40cf52a472ca923db83c722e : option to override FLT_EPSILON with GLM_FLT_EPSILON
https://github.com/recp/cglm/commit/d2e5a3cd5b83c1abc6f4f800c3851c7d44109900 : use epsilon to compare `vec2/vec3/vec4_eq_all`
https://github.com/recp/cglm/commit/f49e8f99914e9739fef1daf47f58748cb749877d : neon: fix vec4_muladds (critical)

1. `glm_vec4_muladds` was using wrong instruction on **NEON** arch, probably copy-paste error
2. `glm_vec2_eq_all` now uses epsilon, because there may be floating point errors, for instance the extracted scale values were: `7.000000477 7.000000477 7.000000000` so using `==` for all values causes test fail...
3. You can change or override epsilon value:

see `common.h`:
```C
#ifndef CGLM_USE_DEFAULT_EPSILON
#  ifndef GLM_FLT_EPSILON
#    define GLM_FLT_EPSILON 1e-6
#  endif
#else
#  define GLM_FLT_EPSILON FLT_EPSILON
#endif
```

Can you try again please?

I think we must add more tests and run ARM tests on Travis-CI...

**Comment by PeterOGB** [comment]
:-) All the tests now pass :-)
Thanks for quick resolution.
PeterO

**Comment by recp** [comment]
Perfect 🤗

Currently test coverage is not 100% but I'll try to make it 100% for all arch over time.

**Feel free to come any other issues, feedbacks, contributions...**

I think we can close this now ;) Hope everything will be fine on NEON, also additional optimizations  for NEON will be available e.g. matrix inverse and more... in the future

**Comment by PeterOGB** [comment]
Closed :-)

**Comment by PeterOGB** [comment]
Just an "FYI", I've built cglm without problems on the new 64bit Raspberry Pi OS.
