### ISSUE TITLE
print functions not working in 0.7.7

### ISSUE THREAD

**Issue by PeterOGB** [recp/cglm#159]
I just upgraded to 0.7.7 and all my debugging output using glm_vec4_print() has disappeared.

**Comment by PeterOGB** [comment]
Seems to be an "undocumented feature" that you need "#define DEBUG 1"  before including the header file !
Also the colour change escape sequences get in the way when viewing a log file rather than viewing output directly in a terminal window!

**Comment by recp** [comment]
Hi @PeterOGB 

Sorry for that. **cglm** tried to disable these print outputs in release mode to optimize your softwares/engines in RELEASE mode (by making these functions NOOP macro). Because sometimes you print and forgot to drop it. You may use prints with your own #ifdefs... of course, that would work. 

The option is documented at https://cglm.readthedocs.io/en/latest/opt.html#print-options , also in RELEASE Notes (https://github.com/recp/cglm/releases/tag/v0.7.3). It would be nice to add it README, sorry again.

I suggest to follow cglm repo by using "Watch" feature of Github. Github also provides to "Watch - Releases Only" if you don't want to get every issue...

For colors, there are a few macros in io.h:

```C
#define CGLM_PRINT_PRECISION    5
#define CGLM_PRINT_MAX_TO_SHORT 1e5
#define CGLM_PRINT_COLOR        "\033[36m"
#define CGLM_PRINT_COLOR_RESET  "\033[0m"
```

print functions use them and we must update this to something like this:

```C
#ifndef CGLM_PRINT_COLOR
# define CGLM_PRINT_COLOR        "\033[36m"
#endif 

#ifndef CGLM_PRINT_COLOR_RESET
# define CGLM_PRINT_COLOR_RESET  "\033[0m"
#endif 
```

this will make colors optional and you will be able to enable/disable colors if you like with this way. I forgot to add `ifndef`...

**Comment by PeterOGB** [comment]
It would have helped me if the Inforrmation about the print  functions needing DEBUG enabled was included in the print functions documentation, which is where I looked! Currently it is a bit hidden (though not intentionally)  in the documentation for the options.

**Comment by recp** [comment]
Most IDEs must define **DEBUG** or **_DEBUG** if debug configuration/mode is enabled. This is why **cglm** checks **DEBUG** or **_DEBUG**. In release/production mode, prints are disabled but if you define **CGLM_DEFINE_PRINTS** macro then print will always be enabled.

now defining these macro as empty must disable colors if you like:

```C
#define CGLM_PRINT_COLOR
#define CGLM_PRINT_COLOR_RESET
```

I updated io documentation (online documentation + header documentation) and made some fixes, also added a note to README.
