### ISSUE TITLE
glm_vec4_copy segfaults with unaligned memory

### ISSUE THREAD

**Issue by Yatima1460** [recp/cglm#51]
I want to notify that glm_vec4_copy crashes if SSE2 is enabled and operates on a vector saved in misaligned memory!

It seems the instruction **_mm_store_ps** segfaults if it operates on non-aligned memory.

I had a struct the size of 20 bytes before an array of vectors and it crashed.
After padding the struct to 24 bytes everything worked perfectly.

I think CGLM should check if memory is aligned or just add it in the documentation as a **big warning**!

**Comment by Yatima1460** [comment]
Found out SSE requires its memory access to be with 16-byte aligned addresses.
Maybe we could add a #define to use **_mm_storeu_ps** and **_mm_loadu_ps**, which are unaligned versions

**Comment by recp** [comment]
> or just add it in the documentation as a big warning!

Actually it is explicitly expressed in docs:
http://cglm.readthedocs.io/en/latest/getting_started.html#aligment-is-required
http://cglm.readthedocs.io/en/latest/troubleshooting.html

For matrix we have this versin:

```C
glm_mat4_ucopy(mat4 mat, mat4 dest) 
```

**u** stands for unaligned. **ucopy** is unaligned version of **copy**. **copy** name was **dup** (duplicate), udup seems weird to me and I had to rename it to copy :)

This version doesn't use SIMD explicitly, I thought that there is vec4_ucopy but it seems I forgot to add it :)

> Maybe we could add a #define to use _mm_storeu_ps and _mm_loadu_ps, which are unaligned versions

Actually instead of macros **cglm** will provide unaligned functions. For instance **glm_vec4_add** is aligned and **glm_vec4u_add** or **glm_uvec4_add** or **glmu_vec4_add** will be unaligned version, check this: https://github.com/recp/cglm/issues/15

Also there is alignment issue for msvc: 

```C
#if defined(_MSC_VER)
#  define CGLM_ALIGN(X) /* __declspec(align(X)) */
#else
#  define CGLM_ALIGN(X) __attribute((aligned(X)))
#endif
```

as you can see I commented align attribute for msvc, because it gave this error[s]:
`formal parameter with requested alignment of 16 won't be aligned`

*I really need help to fix that error :(*

It seems Visual Studio 2017 doesn't complain about this attribute, we may bring it back for VC2017.

IIRC, you are using MinGW and I don't think it will be an issue for you? I think compiler should align vec4/mat4 in struct because of this attribute but I'm not sure. 

We can add vec4_ucopy version which uses `_mm_loadu_ps` instruction  for vec4 quickly, but for other operations it is better to create another namespace as I mentioned above.

**Comment by recp** [comment]
> Maybe we could add a #define to use _mm_storeu_ps and _mm_loadu_ps, which are unaligned versions

Actually this is not bad idea, I'll think on this

```C
#define CGLM_SIMD_LOAD_UNALIGNED
#define CGLM_SIMD_STORE_UNALIGNED
```
this could force all load operations as unaligned for current design

**Comment by Yatima1460** [comment]
> Actually it is explicitly expressed in docs:
http://cglm.readthedocs.io/en/latest/getting_started.html#alignment-is-required
http://cglm.readthedocs.io/en/latest/troubleshooting.html

Oh I meant in the docstring on top the functions!

==========================

> as you can see I commented align attribute for msvc, because it gave this error[s]:
> formal parameter with requested alignment of 16 won't be aligned

Possible reasons:
- __declspec modifier is not permitted on function parameters.
- the stack is guaranteed to be aligned to 16-bytes on Win64 so the compiler can pass it on the stack correctly, but there's no such guarantee on Win32
-

**Comment by recp** [comment]
> Oh I meant in the docstring on top of the functions!

Added to TODOs 👍

> Possible reasons I can think of:
> - the stack is guaranteed to be aligned to 16-bytes on Win64 so the compiler can pass it on the stack > correctly, but there's no such guarantee on Win32
> - __declspec modifier is not permitted on function parameters.

Good catch! I tried to build cglm using VS2015 with x64, build passes, but I tried using VS2015 with x86, build failed due to alignment error. I didn't know Win64 and win32 difference here, thanks for sharing it. 

It seems Visual Studio 2017 fixed it for x86, does it? Because it passes for both x64 and x86.
 
Any suggestions to fix alignment issue on msvc for win32? We can uncomment __declspec(align(X)) for x64, can we? 

Also **__declspec** is not used in function parameters directly, plus **vec4** and **mat4** is array so only pointer will be passed to function, array itself is not passed by value so I think alignment error is ridiculous here. 

A few options:
- we could always use unaligned type like **umat4** and **uvec4** in params
- we could use **vec4*** for mat4 and **float*** for vec4 

I think leaving vec4 and mat4 makes code more readable. Since Visual Studio 2017 skips this error maybe we can also skip it for older compilers :) 

PS: I didn't see or read any official/authoritative statement about skipping/suppressing previous alignment error in VS2017

**Comment by recp** [comment]
@Yatima1460 check this PR: https://github.com/recp/cglm/pull/53 

Now alignment requirement is configurable. Defining `CGLM_ALL_UNALIGNED` macro will force all load and store operations to use simd instruction which does not require any alignment. Maybe we could make this as default behavior in the future.

Also if compiler is msvc and build configuration is 32-bit then this option could be enabled as default.

Could you test it with your previous case without making data aligned?

**Comment by recp** [comment]
[v0.4.5](https://github.com/recp/cglm/releases/tag/v0.4.5) is released and alignment is now optional. Disabling alignment will also disable ALIGN attributes, you can still apply alignment to data yourself. Because accessing aligned data should be faster.
