### ISSUE TITLE
Type Safe Implementation

### ISSUE THREAD

**Issue by jonathanplatzer** [recp/cglm#58]
What is the stance on a type-safe wrapper that utilizes structs or unions instead of arrays?

Is there any interest in a wrapper (kind of like the call "wrapper") that adds type safety?

**Comment by recp** [comment]
**cglm** uses arrays because;

1. It makes possible to load vectors directly to SIMD register. 
2. It makes possible to pass vector/quaternion/matrix... to GL API e.g. OpenGL directly. 
3. It makes possible to iterate members through loop or accessing members by index
4. It makes possible to use similar functions on different types without violating language rules (I guess). For instance using _vec4_ or _vec3_ function on quaternions

If structs were used then to pass struct to SIMD register or OpenGL api;
- struct must be packed; alignment must be disabled
- struct must be casted to array OR if alignment is disabled then the address of struct can be passed directly but this may break/violate language rules (or undefined behavior). 

Both struct and array could be used together as anonymous struct like this:
```C
typedef union vec4 {
    struct { 
        float x;
        float y;
        float z;
        float w; 
    };
    float data[4];
} vec4;
```

but this anonymous struct is C11 feature since cglm is C99 (or C89 + lang extensions). **cglm** may provide this as an option e.g. `#define CGLM_USE_STRUCTS`. With this users can access members via xyzw and can send to apis via data member. This were in my TODOs for a while. If we want to such update like this then it must be common design choice.

Another alternative could be struct wrappers (as you said) to use existing api. This is also not bad idea if there will no undefined-behaviors.

Since there are lot of helpers e.g. glm_vec_add, glm_vec_dot ... maybe accessing members is a rare case?

**Comment by jonathanplatzer** [comment]
Yes, I'm completely with you on the advantages of using arrays for things like SIMD, the OpenGL API and so on.

You built this library with C99 as the target (or even C89 with language extensions), so I wouldn't want to break API compatibility by using anonymous structs/unions from C11. Also, the semantics for accessing variables is a not an issue for me, because in my opinion it doesn't really matter if I have to access things by `a[0]` or `a.x`.

The thing that I'm concerned about is type safety!

The biggest concern for me is code that looks like this:
```c
vec2 a = {1.f, 2.f};
vec3 b = {1.f, 2.f, 3.f};
vec3 c;

glm_vec_mul(a, b, c);    /* this doesn't raise a compile error */
```

While this doesn't look like much, this can get you in serious trouble.
In this case it is not "that" serious, because everything is stored consecutively in memory, you simply would access `b[0]` when trying to access `a[2]` and the result would be wrong.
But, the thing that comes first to my mind is something I would call "Schroedingers Memory Access", where you would use some heap allocated memory instead of the stack.

That's why I would propose something like this, a file like the `call` API/wrapper, that exposes cglm with some kind "typed" interface:
```c
#include "clgm/clgm_typed.h"

vec3 a = GLM_VEC3_ONE_INIT;
vec3 b = {{1.f, 2.f, 3.f}}    /* see remarks (a) */

glmt_vec_mul(a, b, &a);    /* see remarks (b) */
```
and the `clgm_typed.h` would look something like this:
```c
#define vec3 vec3_arr    /* see remarks (c) */

/* [omitted] */

#include "cglm/cglm.h"

/* [omitted] */

#undef vec3

typedef struct _vec3 {
  vec3_arr v;
} vec3;

/* [omitted] */

void 
glmt_vec_mul(vec3 a, vec3 b, vec3* d) {
  glm_vec_mul(a.v, b.v, d->v);    /* see remarks (d) */
}
```

*remarks*
(a) - maybe we provide a macro for nicer initialization syntax (e.g `VEC3_INIT(1.f, 2.f, 3.f);`)
(b) - the `&`-syntax would be unavoidable, but I don't think it would be this big a problem
(c) - this isn't the best way to do this, we could define the types in `cglm/types.h` inside a preprocessed statement, which would handle this automatically
(d) - if we would wrap every function like this, we only would have to dereferenced our destination variable here, because everything else would already be inlined, so I think the compiler would know what to do. I have to say I'm not 100 percent certain about this, (although I tired it, albeit, only with rather straightforward examples), but in my opinion it looks promising.

**Comment by recp** [comment]
> glm_vec_mul(a, b, c);    /* this doesn't raise a compile error */

because there is no error in compile-time.

In C arrays decay to pointer, so vec2, vec3, vec4 all will be decayed to **float*** so there will no compile-time error or warnings because all passed parameters have same type: **float***.

This is not god for type-safety but it is good for some cases:
- I can call vec3 function on vec4: this is valid. For instance I can copy result vec3 into a column of matrix. 

    Here are the examples: https://github.com/recp/cglm/blob/master/include/cglm/affine.h#L173
    https://github.com/recp/cglm/blob/master/include/cglm/quat.h#L654

> While this doesn't look like much, this can get you in serious trouble.

Agree. Users must ALWAYS aware about what they are doing. Because there will no warnings. Type-safety could help here. 

> That's why I would propose something like this, a file like the call API/wrapper, that exposes cglm with some kind "typed" interface
and the cglm_typed.h would look something like this:

Will `#undef vec3` remove original `vec3` type, is this valid? Because `vec3` is typedef not macro. 

`glmt_` seems fine. But there will be half-float and double versions too e.g. `glm64_`, `glm16_` , `glmc16_` ... so there will be lot of name spaces. I don't know maybe it will be hard to maintain all these prefixes in the future.

> (a) - maybe we provide a macro for nicer initialization syntax (e.g VEC3_INIT(1.f, 2.f, 3.f);)

I considered to use `vec3_`, `v3`... name spaces instead of `glm_vec` but the reason I didn't that is that functions with `vec3_` namespace seems like internal. I mean when you see `glm_` function you can ensure that that function comes from a library (actually specific library). But when you read `vec3_`  you don't have any idea where it comes from; library (which library?) or internal code base? I think we must add glm/GLM prefixes to all funcs and macros except types because I like vec3/vec4/mat4 :) 

> (d) - if we would wrap every function like this, we only would have to dereferenced our destination variable here, because everything else would already be inlined, so I think the compiler would know what to do. I have to say I'm not 100 percent certain about this, (although I tired it, albeit, only with rather straightforward examples), but in my opinion it looks promising.

I think compiler (MSVC is not included) would inline wrappers. The actual job is writing and maintaining wrappers :)

If we want to write wrappers I would like to have anonymous struct design. Maybe this could give a change to have that feature. Anonymous struct could be disabled via macros (ifdef). Because all operations will be done using arrays as before. 

Also;

Maybe we could add type-safety by adding attributes to types. For instance Apple's simd library types look like this:

```C
typedef __attribute__((__ext_vector_type__(3))) float simd_float3;
typedef __attribute__((__ext_vector_type__(4))) float simd_float4;
```

When I do this:

```C
simd_float4 a;
simd_float3 b;

simd_distance(a, b)
```

I get this compile error: `No matching function for call to 'simd_distance'` if I make b float4 then it compiles.

What do you think about using attributes? 

Maybe this could save us to write wrappers?

**Comment by jonathanplatzer** [comment]
> What do you think about using attributes?
>
> Maybe this could save us to write wrappers?

Attributes seem very good for this. The thing that I'm concerned about with them is portability. The `__ext_vector_type__(X)` attribute for example is only supported by Clang, for GCC we would have to use `vector_size(X)` as attribute, and for MSVC I have no idea if they have some kind of `__declspec` that supports things like this...

But all in all, yes this would be a very good solution for type safety, and definitely better than a wrapper, which would've been, like you've said, a real hassle to maintain.

**Comment by recp** [comment]
Yes portability is an issue here. Otherwise it provides cool features: https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html

It also allows to return vector type and allows ( + - * / >> << ...) operators, this seems fantastic:

```C
vec3 a, b, c;

/* ... */
a = b + c;
```

after added attribute we don't have to do anything to support this feature.

Maybe we could enable this feature if supported by compiler as alternative syntax:

```C
glm_cross(a, b, c)
```

could be:

```C
vec3 a, b, c;

c = glm_cross(a, b) /* change existing API as an option */
c = glmr_cross(a, b) /* return */
c = glmt_cross(a, b) /* typed */
c = glmv_cross(a, b) /* vectorized */
```

or maybe defining macro like `#define CGLM_USE_VECTOR_TYPES` could translate all APIs to use attribute-d version (there will be lot of `#ifdef`s). In this way existing API will not be broken (I hope). Optional syntax. Everyone will be happy :)

**Comment by jonathanplatzer** [comment]
Yes, I think also that breaking the existing API is a non-option here.

What would you say would be the best course of action getting this thing going?
Is there anything that I can help with?

**Comment by recp** [comment]
> Yes, I think also that breaking the existing API is a non-option here.

Agree, it is not an option
 
> What would you say would be the best course of action to getting this thing going?

Actually I will spend some time on vector attribute later. Since it depends on compilers, why would someone want to rely or build something on specific compilers instead of language standards just for syntax. I'm not sure. 

Maybe we should find alternatives to vector-atribute. 

> Is there anything that I can help you with?

First, I must say that glad to see you here to discuss about design of library. This is a thing. For type safety we still do not have final decision/direction. 

Currently we have a few options:
- wrappers
- option to change types to structure (similar to first)
- vector-size attribute (not portable)
- do nothing
- ? 

I guess we only need type safety for vector types. Because if we pass vector as matrix or vice-versa compiler should raise a warning about incompatible types/pointers. 

You can try these options e.g. wrappers, vector_size attribute... as I will do :) then we can decide which one is better later

**Comment by recp** [comment]
I think adding an option for struct is good idea:

```C
/* types.h */

#if !defined(CGLM_USE_STRUCT) && !defined(CGLM_ANONYMOUS_STRUCT)
#  include "types-array.h"
#else
#  include "types-struct.h"
#endif
```

```C
/* types-array.h */

#if !defined(CGLM_USE_STRUCT) && !defined(CGLM_ANONYMOUS_STRUCT)

#  define GLM_X(V)      V[0]
#  define GLM_Y(V)      V[1]
#  define GLM_Z(V)      V[2]
#  define GLM_W(V)      V[3]

#  define GLM_XREF(V)   V[0]
#  define GLM_YREF(V)   V[1]
#  define GLM_ZREF(V)   V[2]
#  define GLM_WREF(V)   V[3]

#  define GLM_REF(TYPE) TYPE

typedef float                   vec2[2];
typedef CGLM_ALIGN_IF(8)  float vec3[3];
typedef int32_t                 ivec3[3];
typedef CGLM_ALIGN_IF(16) float vec4[4];

#ifdef __AVX__
typedef CGLM_ALIGN_IF(32) vec3  mat3[3];
typedef CGLM_ALIGN_IF(32) vec4  mat4[4];
#else
typedef                   vec3  mat3[3];
typedef CGLM_ALIGN_IF(16) vec4  mat4[4];
#endif

typedef vec4                    versor;

#endif
```

```C
/* types-struct.h */

#if defined(CGLM_USE_STRUCT) || defined(CGLM_ANONYMOUS_STRUCT)

#  define GLM_X(V)      V.raw[0]
#  define GLM_Y(V)      V.raw[1]
#  define GLM_Z(V)      V.raw[2]
#  define GLM_W(V)      V.raw[3]

#  define GLM_XREF(V)   V->raw[0]
#  define GLM_YREF(V)   V->raw[1]
#  define GLM_ZREF(V)   V->raw[2]
#  define GLM_WREF(V)   V->raw[3]

#  define GLM_REF(TYPE) TYPE *  

typedef union vec3 {
#ifdef CGLM_ANONYMOUS_STRUCT
  struct {
    float x;
    float y;
    float z;
  };
#endif
  CGLM_ALIGN_IF(8) float raw[3];
} vec3;

typedef union vec4 {
#ifdef CGLM_ANONYMOUS_STRUCT
  struct {
    float x;
    float y;
    float z;
    float w;
  };
#endif
  /* I'm not sure if this is the right place or not to specify alignment, 
     maybe we could move this to before struct  */
  CGLM_ALIGN_IF(16) float raw[4]; 
} vec4;

/* ... other types are similar ... */

#ifdef __AVX__
typedef CGLM_ALIGN_IF(32) float mat3[3][3];
typedef CGLM_ALIGN_IF(32) float mat4[4][4];
#else
typedef                   float mat3[3][3];
typedef CGLM_ALIGN_IF(16) float mat4[4][4];
#endif

#endif
```

Example API implementation (`glm_vec_mul`):
```C
/* old */
CGLM_INLINE
void
glm_vec_mul(vec3 a, vec3 b, vec3 d) {
  d[0] = a[0] * b[0];
  d[1] = a[1] * b[1];
  d[2] = a[2] * b[2];
}

/* new */
CGLM_INLINE
void
glm_vec_mul(vec3 a, vec3 b, GLM_REF(vec3) d) {
  GLM_XREF(d) = GLM_X(a) * GLM_X(b);
  GLM_YREF(d) = GLM_Y(a) * GLM_Y(b);
  GLM_ZREF(d) = GLM_Z(a) * GLM_Z(b);
}
```

I think this wont break existing API. As you can see all are options, alternative syntax. It also provides optional anonymous struct syntax. If it is not enabled then your proposed syntax will be activated by CGLM_USE_STRUCT.

Also in the future we can provide another option to change signature of func to allow returning these structs (only for inline functions), nothing will have happened to compiled version.

By using GLM_X/GLM_Y/GLM_Z and REF (pointer) versions, we do not need to duplicate functions or write wrappers (if we don't want to?). 

What do you think?

**Comment by recp** [comment]
UPDATE:

I removed GLM_ prefix from helper macros cglm headers, now it looks more clear:

```
/* common.h */
#define X      GLM_X
#define Y      GLM_Y
#define Z      GLM_Z
#define W      GLM_W
#define REF    GLM_REF
/* ... */
```

```C
/* old */
CGLM_INLINE
void
glm_vec_mul(vec3 a, vec3 b, vec3 d) {
  d[0] = a[0] * b[0];
  d[1] = a[1] * b[1];
  d[2] = a[2] * b[2];
}

/* new */
CGLM_INLINE
void
glm_vec_mul(vec3 a, vec3 b, REF(vec3) d) {
  XREF(d) = X(a) * X(b);
  YREF(d) = Y(a) * Y(b);
  ZREF(d) = Z(a) * Z(b);
}
```

I'm restoring these X, Y, Z... macros in end of header by including new `common-end.h` header. So it is safe to use them. Now it looks more readable. Also compiler raises an error (not warning) if I use vec3 function on vec4... perfect!

I will inspect assembly output later.

**Comment by acoto87** [comment]
Hi, I don't know what's the state of the development of this. Since you are adding an option to use structs instead of arrays, can the operations return the result instead of passing the destination as the third parameter? 

That would allow code like:

```c
vec3 a = ...;
vec3 b = ...;

// compute some result with two input vectors
vec3 c = glm_vec3_add(a, b);

// normalize the vector
vec3 n = glm_vec3_divs(c, glm_vec3_norm(c));
```

I know since its inception `cglm` is using the last parameter as the destination, but probably that was because of the limitation of C to return arrays. This change would allow code to be more compact for simpler operations when one can pass directly the result of one function into another. I know that this is not desirable for complex operations (since C doesn't have operator overloading), but I think that the decision to use one way or another should be in the hands of the user of the library.

What do you think?

**Comment by acoto87** [comment]
I read the whole thread again, and your proposal about the structs seems feasible to me. I like that with that option there no need for wrappers.

Although, taking a look about the returning structs instead of passing a reference:

```c
/* new */
CGLM_INLINE
void
vec3 glmr_vec_mul(vec3 a, vec3 b) {
  vec3 r = glm_vec3_zero();
  glm_vec_mul(a, b, &r);
  return r;
}
```

Would this kind of wrappers needed then?
And the `CGLM_ANONYMOUS_STRUCT` wouldn't work on C99, right?

**Comment by recp** [comment]
`glmr_` is not bad but there maybe better namespaces for structs like `glms_` or `glm_svec3_`... maybe.

Struct wrapper could be:

```C

// svec3.h or vec3-struct.h ...

CGLM_INLINE
svec3
glms_vec3_mul(svec3 a, svec3 b) {
  vec3s tmp;
  glm_vec3_mul(a.raw, b.raw, tmp.raw); /* call existing array api, svec3.raw is vec3 */
  return tmp;
}

// alternative namespace glm_svec3_mul(svec3 a, svec3 b)
```

**vec3** is array so I used new type called `svec3`, it could be `vec3s` or something else. I want to keep existing array api because I like it and there are some benefits to use arrays... It would be nice to bring type safety for array api too 😔 maybe compiler specific attributes, flags can help here; I don't know yet.

> And the CGLM_ANONYMOUS_STRUCT wouldn't work on C99, right?

Actually it may work with language extensions; afaik gcc, clang... support anonymous structs in previous C versions as extension

**Comment by acoto87** [comment]
Yes, your `glms_vec3_mul` make much more sense. I didn't notice what I wrote doesn't compile if vec3 is a struct and `glm_vec3_mul` is the regular array function :sweat_smile:.

So, I like the `vec3s` syntax, the `3` separate very well the base type and the implementation, meaning this is a `vec3` but with structs `s`. Also, the `glms_` namespace to be consistent.

> Actually it may work with language extensions; afaik gcc, clang... support anonymous structs in previous C versions as extension

I think tomorrow I'm going to make some tests about this.

I think it could be worth to explore the vector extensions of GCC and Clang, the only question is if MSVC support something similar. If those extensions have the same features, then type safety could be brought to the array api with compiler flags.

**Comment by acoto87** [comment]
Well, I did some tests about the conformance of anonymous/unnamed fields within structs/unions, and it's true that GCC and Clang support that with extensions when -std=c99 is specified. Although with the -Wpedantic flag they will throw a warning about it. MSVC doesn't completely support C99, and afaik currently there is no way to specify any C standard version to the compiler, it throw the warning anyway., Some tests here: https://godbolt.org/z/dwRr37.

**Comment by acoto87** [comment]
I did some other tests about the vector extensions of GCC and Clang: https://godbolt.org/z/Q2W82V

I think it could work with some macros, but one throwback is that the size of the vectors in GCC must be power of two, so it will complaint for something like 

```c
typedef float vec3 __attribute__ ((vector_size (12)));
```

Thoughts?

**Comment by recp** [comment]
Thanks for these tests

>  Although with the -Wpedantic flag they will throw a warning about it.

It gives warning but still working, so better than nothing. Consider a struct like this:

```C
typedef union vec3s {
#ifndef CGLM_NO_ANONYMOUS_STRUCT
  struct {
    float x;
    float y;
    float z;
  };
#endif
  vec3 raw;
} vec3s;
```

users can disable anonymous structs by defining `CGLM_NO_ANONYMOUS_STRUCT` macro (just want to type safety)

With struct api (wrapper) user can also pass struct to array api to pass struct as reference:

```C
 // struct api
vec3s cross = glms_cross(a, b);


// pass struct as reference by using array api
vec3s cross;
glm_vec3_cross(a.raw, b.raw, cross.raw);
```

this seems good design to me and should be implemented asap.

---

It seems we can't use vector extensions right now, in the future thing may change. +1 for structs wrappers.

---

This is also an option (see my previous comments) but separate wrappers will make things more neat/clear I guess. 

```C
CGLM_INLINE
void
glm_vec_mul(vec3 a, vec3 b, REF(vec3) d) {
  XREF(d) = X(a) * X(b);
  YREF(d) = Y(a) * Y(b);
  ZREF(d) = Z(a) * Z(b);
}
```
(user can switch between array and struct api, can't use both here)

**Comment by acoto87** [comment]
Sounds good, I think it could be good to have those structs types and I agree that separate wrappers will make things more clear.

So, will you implement those wrappers with the proposal of `types-struct.h`, can I do it, make a proper PR and iterate on it until we get a good solution? 😃

**Comment by recp** [comment]
Hi @acoto87 

> can I do it, make a proper PR and iterate on it until we get a good implementation? 😃

sure. I'll wait a proper PR ;)

**Comment by soulfoam** [comment]
I'll implement this right now as @recp has proposed, as I also think this is the best method for doing this.

Personally, I think the union/anonymous structs should be the **default** option for cglm. So vec3 is by default a union, and vec3a can be for the array type.

Here's a couple reasons why:

1. The type safety is of course one of the biggest reasons. We all know it's easy enough to make an error, and there's no such thing as a perfect programmer. 

2. Being able to return the union in a function is so, so useful. It is much more clear what is going on.

```
mat4 projection;
camera_get_projection(cam, projection)
```
is definitley less clear and ugly than

`mat4 projection = camera_get_projection(cam)`

3. Clarity and explicitness of code, with the anonymous structs, this is much more clear

```
vec3 pos = glm_vec3(0, 0, 0);
pos.x = 10;
pos.y = 5;
pos.z = 2;
```

than

```
vec3 pos = {0, 0, 0};
pos[0] = 10;
pos[1] = 5;
pos[2] = 2;
```

For example, I use Z up in my engine, which is of course aribtrary, but there are times where I am doing:

```
pos[0] = 10;
pos[2] = 2;
pos[1] = 5;
```

and although using 0-1-2 is almost as readable as x-y-z, it still takes an extra second to make sure that 2 is Z and 1 is Y. Also, to other people reading the code, it may not be clear what is held at 0-1-2, while x-y-z is explicit. 

4. When using unaligned types, you aren't forced to use glm_copy, and can simply use assignment.

The only downfall is that you can't pass this data directly to OpenGL or the likes without using .raw, but this is easily solved with having a wrapper, which you should anyway, such as:

```
void 
shader_set_vec3(shader_t shader, const char *name, vec3 value)
{
	glUniform3fv(glGetUniformLocation(shader, name), 1, value.raw);
}
```

This would be extremely easy to implement, as the union/anon structs would just be wrapper calls to the array functions passing in .raw as @recp has mentioned, but I really think they should be the default option.

**Comment by recp** [comment]
Hi @soulfoam 

Thank you for your comments, it makes me happy to see **cglm**'s community/contributors is growing 🤗

Making union/anonymous structs the default would an option but first we must implement union/anonymous structs. In the future we may decide to make it default but I think we should keep arrays as default for now (or until struct api got its shape), I don't know; we should get more feedbacks to make it default. 

`glm_vec3` (struct) and `glm_vec3a` (array) seems good, but `glms_vec3`/`glm_vec3s` (struct) also good. 

Recently @acoto87 started to work on this #80 , any feedbacks/reviews are welcome there

**Comment by recp** [comment]
The type safety is implemented as structs at https://github.com/recp/cglm/pull/80 (thanks to @acoto87 )

if anyone else has better ideas feel free to create new issue to discuss...
