### ISSUE TITLE
Binary Constants in AVX implementations

### ISSUE THREAD

**Issue by jonathanplatzer** [recp/cglm#62]
While playing with various compiler flags on my machine with AVX support, I noticed that you are using binary constants in the `mm256_permute` functions, which are GCC extensions. This could lead to some problems when trying to compile on MSVC, but it is also not supported when using ISO C99. 

The question is now if we should just change these to hex constants or do something like this to make it more readable:
```c
#if _GNUC_
  s1 = 0b00000011;
#else
  s1 = 0x3;
#endif
y4 = _mm256_permute2f128_ps(y2, y2, s1);
```

**Comment by recp** [comment]
@jonathanplatzer I didn't aware that binary constants are GCC extensions, thanks.

Maybe we can always use hex instead of if/else?

To make it more readable, I think we could add comments, for your case:
```C
y4 = _mm256_permute2f128_ps(y2, y2, 0x03); /* 0x03: 0b00000011 */
```

or a macro could help to make it more readable maybe. Because macro name could give us an idea what control/imm parameter does.

I'll read Intel Intrinsics Guide asap to remember control parameter (last parameter) usage. 

If you would like to fix it, a PR is welcome ;)
