### ISSUE TITLE
name change for glm_euler_sq

### ISSUE THREAD

**Issue by superbigio** [recp/cglm#93]
Hi,

This is a minor suggestion. I find glm_euler_sq a little misleading as a name since the accepted convention in c (and other languages) is for "sq" as an abbreviation to usually mean square or squared (e.g. sqrt()). Why don't you change the name to glm_euler_seq? It is only a character longer but it conveys the meaning much more clearly. Alternatively, since I suspect this enum won't be used very often you could also go with glm_euler_sequence without the need of shortening the name.

**Comment by recp** [comment]
Hi @superbigio 

Thanks for your proposal!

> Why don't you change the name to glm_euler_seq?

Because I like short names :)

Yes `glm_euler_seq` seems better one. Would you like to create a Pull Request? Or I can add it to my TODOs.

We should maintain thee old type for a while, to do that we could use something like this:

```C
typedef glm_euler_seq glm_euler_sq;
```

In this way the change will be compatible with previous versions...

FWIW, there is also another issue about Euler angles: https://github.com/recp/cglm/issues/30

**Comment by superbigio** [comment]
Hi Recep,
sorry for my late reply...Yes, I'll create a Pull request right away.
There are also some features I would like to add and issues I would like to resolve.Yes, the issue about Euler angles is one of them.
I will open issues on Github as I move forward so we can discuss everyone of them.
Best
- Luigi
    On Saturday, August 17, 2019, 8:13:23 AM GMT+2, Recep Aslantas <notifications@github.com> wrote:  
 
 
Hi @superbigio

Thanks for your proposal!


Why don't you change the name to glm_euler_seq?


Because I like short names :)

Yes glm_euler_seq seems better one. Would you like to create a Pull Request? Or I can add it to my TODOs.

We should maintain thee old type for a while, to do that we could use something like this:
typedef glm_euler_seq glm_euler_sq;
In this way the change will be compatible with previous versions...

FWIW, there is also another issue about Euler angles: #30

**Comment by recp** [comment]
This is fixed at https://github.com/recp/cglm/pull/94
